### PR TITLE
Fix symlink creating for images

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by velnias75** [comment]
Just the quotes please, see our conversation (sorry, link not at hand)

**Comment by hasufell** [comment]
Why? It's incorrect with DESTDIR in the source part of ```ln```.

**Comment by velnias75** [comment]
'$DESTDIR' is a user-provided variable almost always empty.
The use of '$DESTDIR' is to *prefix* an installation. This is used i.e. for image build as done in *Gentoo* and *Debian*, but almost never for tarball installs.

**Comment by hasufell** [comment]
> '$DESTDIR' is a user-provided variable almost always empty.
> The use of '$DESTDIR' is to prefix an installation. This is used i.e. for image build as done in Gentoo and Debian, but almost never for tarball installs.

I know. It still doesn't explain why the patch is incorrect. Please test it locally.

**Comment by velnias75** [comment]
Ok, I'll merge it in and test it again, but my first attempt was the same like yours with the result of linking **inside** the build directory.

**Comment by velnias75** [comment]
Shame on me. Have it been the missing quotes or did my beloved cat demanded attention while I was trying it??

    touhami3 netmaumau # ls -l /tmp/nmm/usr/local/share/netmaumau/
    insgesamt 152
    lrwxrwxrwx 1 root root     6 17. Jan 18:43 ai_img1.png -> QS.PNG
    lrwxrwxrwx 1 root root     6 17. Jan 18:43 ai_img2.png -> KC.PNG
    lrwxrwxrwx 1 root root     6 17. Jan 18:43 ai_img3.png -> QC.PNG``

**Comment by velnias75** [comment]
Grmphl, now I remember: *Debian* `dh_links` script wnats the opposite order which confused me...

**Comment by hasufell** [comment]
See my rant about debian here https://github.com/hasufell/games-overlay/pull/9#issuecomment-70376822 ;)

**Comment by velnias75** [comment]
Ok, but please don't let us get a war about the only right and true Linux distro.
My sister loves Linux, but if I would recommend her *Gentoo* she would probably decide to back to *Atari ST* :grinning: 

Her biggest enemy on Linux is the console. I tried hard, but she simply don't understand that the first word is the **command** the others are options to the **command** and all is separated by a blank.

**Comment by hasufell** [comment]
I've never really recommended gentoo to anyone. It's not really for wide audience in the first place and has a lot of problems which will probably never be fixed.

My point is that every distro is broken. Gentoo just makes it easier for me to fix/manipulate/mess with random packages than other distros do. Messing with toolchain or other non-trivial packages on ubuntu is a really hard task.

**Comment by velnias75** [comment]
My final decision to move to *Gentoo* was /is the absolutely easy way to port my apps to Winf*ck.
This was a hard task on Debian :sad:

**Comment by velnias75** [comment]
BTW: we can be lucky with every Linux distro, even if totally broken it is never that broken as Winf*ck.
Browse the code of NetMauMau and search for `#ifdef _WIN32`/`#ifndef _WIN32` and you will understand!

**Pull request merged**
